### ISSUE TITLE
Compilation Timeout

### ISSUE THREAD

**Issue by mazum21** [ashish10alex/vscode-dataform-tools#10]
Would be nice to be able to set timeout option (--timeout) in the VS Code setting. Our project size leads to compilation time > ~8 seconds, which leads to following error:
`Dataform encountered an error: Compilation timed out`

Compilation via CLI is working with this command:
`❯ dataform compile --timeout 1min`

**Comment by ashish10alex** [comment]
Hi @mazum21 , thanks for raising the issue, the issue has now been fixed. Please use the latest release [0.0.37](https://marketplace.visualstudio.com/items?itemName=ashishalex.dataform-lsp-vscode). 

MR that fixed the issue: https://github.com/ashish10alex/vscode-dataform-tools/pull/11

**Comment by mazum21** [comment]
Hey @ashish10alex  thanks for the quick fix. Awesome product by the way :)

I just realized that the compilation timeout also occurs the executing "Dataform: run current file". Seems like the timeout option is not added to `dataform run` commands. Apparently `dataform run` commands also trigger a compilation.

**Comment by ashish10alex** [comment]
Thanks @mazum21  for reporting the follow up issue 
Please switch to the latest release [0.0.38](https://marketplace.visualstudio.com/items?itemName=ashishalex.dataform-lsp-vscode) where you be able to run file / tag without issues 

--- 
Please feel free to report any other issues / feedback / feature requests that you might have :)
