### ISSUE TITLE
Support for gcloud auth

### ISSUE THREAD

**Issue by mazum21** [ashish10alex/vscode-dataform-tools#15]
It seems that currently only GCP authentication with credential JSON file is supported:
`> Dataform encountered an error: Missing credentials JSON file`

I would appreciate support for `glcoud auth login` -> https://cloud.google.com/sdk/gcloud/reference/auth/login

**Comment by ashish10alex** [comment]
Hi @mazum21 , 
If if I understood the error correctly, you might be missing running `dataform init-creds` command at the root of your repository. This will allow dataform to use the credentials generated by `gcloud auth application-default login`. as shown in the screenshot below. Please refer to [FAQ(3)](https://github.com/ashish10alex/vscode-dataform-tools/tree/main#frequently-asked-questions) for more details.  Please let me know if this solves the issue ? 



![358568711-e7936c14-aaa0-49d3-9274-10cac1895539](https://github.com/user-attachments/assets/18cb6db8-5314-4a23-ba41-aae419a5b430)

**Comment by mazum21** [comment]
Thanks @ashish10alex, this was the missing piece. Now it's working as expected!
