### ISSUE TITLE
File type not supported. Supported file types are sqlx, js

### ISSUE THREAD

**Issue by mazum21** [ashish10alex/vscode-dataform-tools#19]
This Dataform tools error message appears again and again. I cannot find a file with other file types, excep from .gitignore and .gitkeep.

![image](https://github.com/user-attachments/assets/9b2a4879-cd39-4bde-9a54-3324dc8791c2)

**Comment by ashish10alex** [comment]
Hi @mazum21 , this was definitely an issue in a previous version. Can you please confirm if this is still an issue when you are using version 0.0.47 ?

**Comment by mazum21** [comment]
It's gone 😊 Thanks @ashish10alex 👌
