### ISSUE TITLE
Unable to detect a Project Id in the current environment. 

### ISSUE THREAD

**Issue by floyergilmour** [ashish10alex/vscode-dataform-tools#21]
Hi I'm getting this annoying error: How do I add a project ID in the current environment. How do I fix it?
<img width="791" alt="image" src="https://github.com/user-attachments/assets/9da31532-a00e-42ab-80a5-12e9a78450dd">

**Comment by ashish10alex** [comment]
Hi @floyergilmour , looks like you are missing the step 2 of requirements which is [setting up default application credentials for GCP](https://github.com/ashish10alex/vscode-dataform-tools?tab=readme-ov-file#requirements). 

You can follow the [following guide](https://cloud.google.com/docs/authentication/provide-credentials-adc) to set it up. Once that is setup, the error should go away. You then can verify if you gcp project is correctly setup using  

```
gcloud config get-value project
```

This will show you your current gcp project.  Please let me know if this works for you

**Comment by benjaminwestern** [comment]
@floyergilmour please following the 'Google' component of the [Development Requirements](https://github.com/benjaminwestern/dataform-testing?tab=readme-ov-file#requirements) here, if you still have issues, please feel free to reach out!
