### ISSUE TITLE
Incorrect files compiled, run when using ${ref("...", "...")} references

### ISSUE THREAD

**Issue by langabi** [ashish10alex/vscode-dataform-tools#25]
Our repository has multiple instances of the same table name (e.g., fact_order) in different datasets (named after legal entities). We use ${ref("...", "...")} syntax to declare dependencies, and `schema: "...",` lines in the config {} block at the top of each transformation.

Dataform tools is frequently acting on the wrong file, for example:
- automatic compilation on save, and errors resulting from this
- "run" cmd runs the wrong file (wrong dataset)

I'm not sure how it's choosing which version to use, looks plausibly alphabetical.

Thanks for a great tool otherwise!

**Comment by ashish10alex** [comment]
Hi @langabi 
Thanks for creating the issue. The issue with possibly wrong file being ran/compiled when there are multiple files with same table names but different dataset might be originating from the logic on how I was verifying which file to run / compile. I have [shipped a fix](https://github.com/ashish10alex/vscode-dataform-tools/commit/26b6d442f9e8088a6f01cfccdfe42e7812ee558d) for the issue in the recent release `v0.0.52`. 

Please let me know if it works for you :)

**Comment by langabi** [comment]
This is amazing! I was just busy creating a test case to help you debug this issue, and you've already solved it! Seems to be working fine now, thanks so much!
