### ISSUE TITLE
Unexpected Behavior with "Dataform: Run file(s) / tag(s) with options" Command

### ISSUE THREAD

**Issue by j0nandr1** [ashish10alex/vscode-dataform-tools#27]
Hi, I'm experiencing an issue with the "Dataform: Run file(s) / tag(s) with options" command.
When I try to execute 
 - run a tag 
 - run type -> default 
 - full refresh -> yes

But it only adds these parameters --tags=update_test_tables --include-deps to the Dataform run command. 
As a result, it try to run all dependencies and no full refresh. But I would expect, that it runs no dependents or dependencies and a full refresh.

Can this be fixed, or am I messing up somewhere?

**Comment by ashish10alex** [comment]
Hi @j0nandr1 , 
Thanks for raising the issue. Please upgrade to the latest version `v0.0.60` where this issue should be fixed. 
Please let me know if this works for you :)

**Comment by j0nandr1** [comment]
Hi @ashish10alex, thanks for the quick reply. Now it added the --full-refresh and removed the --include-deps parameter. But the --tags= is missing.

**Comment by ashish10alex** [comment]
Hi @j0nandr1 ,  
Apologies, just shipped a fix now. Please try `v0.0.61` and let me know if it works as expected ? 
--
Also, I was interested in how did you know about the extension / this feature as I had just shipped the feature.  Was interested in how you came about using the extension. Additionally, please feel free to create an issue for any feature request you might have .

**Comment by j0nandr1** [comment]
No problem, thanks for the fast fix! Now, it works as expected.

A work colleague showed me the extension and was the one who requested this feature.
