### ISSUE TITLE
"Dataform: Run file(s) / tag(s) with options" question

### ISSUE THREAD

**Issue by Kulja** [ashish10alex/vscode-dataform-tools#31]
First, great extension!

I was wondering if there is a way to add/change a variable when running "Dataform: Run file(s) / tag(s) with options" e.g. using `--vars=sampleVar=sampleValue`?

My end goal is to have a way to change a variable value when running a file but ideally, I would like to be able to set it once so that anytime I run a file it always uses that variable value.

Thanks!

**Comment by ashish10alex** [comment]
Hi @Kulja , thank you. The requested feature does not yet exist, however can be added. I'll message here once the feature has been implemented and released.

**Comment by ashish10alex** [comment]
Hi @Kulja, the requested feature has now been made available in `v0.2.6`. compiler option can be added in the vscode settings as shown in the screenshot below. Please let me know if this works for you 

![CleanShot 2024-10-11 at 22 07 16@2x](https://github.com/user-attachments/assets/3df4091b-2000-4c16-acb3-abb54abe49f7)

**Comment by Kulja** [comment]
@ashish10alex works great! It works for all dataform run commands afaik and that is even better. 

Thank you!

**Comment by ashish10alex** [comment]
awesome, thanks for clarifying. Yes, I had passed in the variable to other relevant Dataform commands.

**Comment by Kulja** [comment]
it appears that if I use the setting above eg `--var=someKey=whatever` that properties in my `.df-credentials.json` file get ignored (well, at least location does). 

This is my `.df-credentials.json` file: ```{
    "projectId": "some-project-id",
    "location": "europe-west2"
}``` and if I am using the `--var=someKey=whatever` I am getting errors when I try to run assertions that my table was not found in location `US`. If I remove `--var=someKey=whatever` it works just fine.

what am I missing?

**Comment by ashish10alex** [comment]
Hi, are you able to replicate the same error when trying to run the assertion using dataform cli ? 
if so you might need to check default location settings of your gcloud using `gcloud config configurations list` and look for the `COMPUTE_DEFAULT_REGIOIN`

---

**Comment by Kulja** [comment]
Ok, I tried a couple of things and it looks like it is working just fine with Visual Studio Code but it has this problem when I am using Cursor.

Sorry for raising this issue.
