### ISSUE TITLE
Bug: The dataform tags are not updated

### ISSUE THREAD

**Issue by TheSmartMonkey** [ashish10alex/vscode-dataform-tools#33]
## Description

While running the command "Dataform: Run a tag with dependents" with ctrl + shift + P The tags are not up to date
I have to reload vscode to fix it

## Steps to Reproduce (for bugs)

1. Modify a tag name in a sqlx file
2. ctrl + shift + P
3. Select  "Dataform: Run a tag with dependents"
4. Your new tag is not in the list
5. Reload vscode
6. ctrl + shift + P
7. Select  "Dataform: Run a tag with dependents"
8. You tag is in the list

## Expected Behavior

No need to reload vscode the tags are up to date

## Actual Behavior

The tags are not up to date

## Environment

- **Device:** Desktop
- **OS:** macOS
- **Editor** Cursor vscode version

```sh
Version: 0.42.2
VSCode Version: 1.93.1
```

**Comment by ashish10alex** [comment]
Hi @TheSmartMonkey,
thanks for raising the issue, for the tag to show after adding them you would need to save the file so that compilation is triggered. This is when the tags/dependencies get updated. 
---
Please let me know if the issues still persists

**Comment by TheSmartMonkey** [comment]
Ok you are right I tried multiple times and it works my bad

**Comment by TheSmartMonkey** [comment]
Ok you are right I tried multiple times and it works my bad
