### ISSUE TITLE
Feature request: Search by tags in Dataform dependancy graph

### ISSUE THREAD

**Issue by TheSmartMonkey** [ashish10alex/vscode-dataform-tools#36]
## Summary

Be able to search by tags in Dataform dependancy graph

## Motivation

See the full pipeline, useful when you have a lot of pipelines

## Detailed Description

In dataform google ui

![image](https://github.com/user-attachments/assets/e19cfa53-400f-4d6a-8d1b-2b8b14d9562d)

Add an option to search by tags

![image](https://github.com/user-attachments/assets/e69687d3-7a70-4489-9923-1fd39ca62691)

## Expected Behavior

1. Have an option to search by tags in dependencies graph (could be another dropdown or a third option in upstream / downstream)
2. Could be cool to add a vscode command with ctrl + shift + P (on current file tags in  dependancy graph and/or on all the tags)

**Comment by ashish10alex** [comment]
Hi @TheSmartMonkey , please try the latest release `v0.2.14` that has the requested feature. 

---

1. User can selected a tag from the available tags from the web ui 
2. The options for the root node will be filtered to have only the nodes of the requested tag
3. The tree is re-drawn by picking the first element from the filtered list. If you would like to see specific upstream / downstream dependency of a node for the the tag this can be achieved by selected it from the dropdown menu
4. To go back to default view of all tags & nodes, you can select "all" option in tags dropdown. Now that I think of it, if someone names their tag as "all" it would not filter as expected 

---

I have not implemented the keyboard shortcut for this feature as of now as it will be something that I think will be used scarcely. But can review this decision in future. Please let me know if it works for you :)

**Comment by TheSmartMonkey** [comment]
Hey @ashish10alex this is great man !
The only thing that could be improved from what I see is when I do a search by tag pretty mush all the time I want the full pipeline and not upstream / downstream

Currently : 
![image](https://github.com/user-attachments/assets/2546d78c-51a9-4b76-b7e3-960f4d06c9d7)

Full pipeline : 
![image](https://github.com/user-attachments/assets/02e08677-971a-401c-8fea-1e1a52ecc349)

This is the example of a simple pipeline but when I have assertions I could have a lot of dependencies and clicking on each nodes to display the full pipeline could be painful

For your select "all" option in tags dropdown issue I didn't look at your code but you can maybe display "all" in the frontend but in the backend do a match to some kind of tag with a unique id

**Comment by ashish10alex** [comment]
Hi @TheSmartMonkey , 
Please update to the latest version `v0.2.17` . I have added two buttons `expand all` and `collapse all` which should easily let you expand the tree. However for seeing the entire graph, I am largely limited by the [library I am using](https://github.com/square/dependentree). Although I have been able to make some changes to the library by add colours for different datasets. Changing it to show the whole graph is a non-trivial change. 

---

The current implementation servers most use cases for me, e.g. seeing the dependents and dependencies of a node easily, identify sources associated with the nodes and traversing to the file where source is defined  by clicking on it. 

---

However, there is definitely scope for improvement, so please feel free to submit a PR :)
