### ISSUE TITLE
Improved Language Support and Snippets for SQL

### ISSUE THREAD

**Issue by HampB** [ashish10alex/vscode-dataform-tools#40]
It would be helpful to have enhanced language support and relevant snippets for the SQL parts of .sqlx files. This would make working with SQL in these files more efficient.

For comparison, similar features are available in the [vscode-language-sql-bigquery extension](https://github.com/shinichi-takii/vscode-language-sql-bigquery), which could serve as a useful reference.

Understandable if this is not in scope for this repo, but it would be a nice improvement.

**Comment by ashish10alex** [comment]
Hi @HampB , thanks for the suggestion. This would be something I'll be happy to add. Would you think it would be beneficial to include everything [they have](https://github.com/shinichi-takii/vscode-language-sql-bigquery) and give the authors the credit ?

**Comment by HampB** [comment]
I do believe it would be beneficial to just include it all. 
I’ve not done any rigorous testing, but from the testing I’ve done it seems quite complete and the snippets are good.

**Comment by ashish10alex** [comment]
Hi @HampB , I have added all the snippets from the suggested repo. I have also linked the repo in the README of this extension so that the author gets appropriate credit. 

---
Please update to the latest version of the extension `v0.2.20` where the snippets should be available

**Comment by HampB** [comment]
Works great, thanks!
