### ISSUE TITLE
Issue: Columns with Empty Arrays Disappear in Preview Query

### ISSUE THREAD

**Issue by HampB** [ashish10alex/vscode-dataform-tools#42]
When using the preview query feature, columns containing empty arrays seem to disappear from the output. 

#### Steps to Reproduce

1. Run the following SQL:

   ```sql
   config {
     type: 'table',
     schema: 'exports'
   }

   WITH cte AS( 
     SELECT 
         id,
         ARRAY(
           SELECT AS STRUCT * FROM UNNEST([]) AS EmptyArrayCol
         ) AS EmptyArray,
         ARRAY(
           SELECT AS STRUCT * FROM UNNEST(GENERATE_ARRAY(1, 3)) AS PopulatedArrayCol
         ) AS PopulatedArray
       FROM UNNEST(GENERATE_ARRAY(1, 3)) AS id
   )

   SELECT * FROM cte
   ```

2. View the query preview.

#### Expected Behavior

The preview should display both `EmptyArray` and `PopulatedArray` columns, even if `EmptyArray` contains an empty array.

#### Actual Behavior

The `EmptyArray` column is missing from the preview when it contains an empty array, as shown in the screenshot below:

![image](https://github.com/user-attachments/assets/f85879ee-9bf9-4b1f-9440-53f633fe77fd)

**Comment by HampB** [comment]
It seems like the same behavior occurs when dealing with an array of non-struct elements.
```sql
ARRAY<STRING>['string1', 'string2', 'string3'] AS StringArray,
```

**Comment by ashish10alex** [comment]
Hi @HampB , 
Thanks for reporting the issue. Please update to the latest version `v0.2.22` where this issue should be fixed. The preview query results is very much a beta for any non-trivial data structures due to the complexity involved in showing nested data while using an external table library + handling different BigQuery data types. So please feel free to report any other issue that you may come across. 
I have tested the following which seems to work as expected 

```sql
WITH cte AS( 
  SELECT 
      "my_data" as foo,
      id,
      ARRAY<STRING>['string1', 'string2', 'string3'] AS StringArray,
      ARRAY(
        SELECT AS STRUCT * FROM UNNEST([]) AS EmptyArrayCol
      ) AS EmptyArray,
      ARRAY(
        SELECT AS STRUCT * FROM UNNEST([]) AS AnotherEmptyArrayCol
      ) AS AnotherEmptyArrayCol,
      ARRAY(
        SELECT AS STRUCT * FROM UNNEST(GENERATE_ARRAY(1, 3)) AS PopulatedArrayCol
      ) AS PopulatedArray,
      ARRAY(
        SELECT AS STRUCT * FROM UNNEST(GENERATE_ARRAY(1, 5)) AS PopulatedArrayMoreItems
      ) AS PopulatedArrayMoreItems,
      ARRAY(
        SELECT AS STRUCT * FROM UNNEST(GENERATE_DATE_ARRAY(CURRENT_DATE(), CURRENT_DATE() + 6, INTERVAL 1 day)) AS dateArray
      ) AS dateArray,
    FROM UNNEST(GENERATE_ARRAY(1, 2)) AS id
)

SELECT * FROM cte
```

![CleanShot 2024-11-07 at 21 45 14@2x](https://github.com/user-attachments/assets/7cbcf3f4-76f2-464f-a41a-4ff8aec47f97)

**Comment by HampB** [comment]
Once again, thanks for the quick resolutions!

The examples are working well, but I encountered issues with production data. When a column contains a mix of populated and empty arrays, it throws the error: 
> "Cannot read properties of undefined (reading 'length')"

This issue can be reproduced with the following SQL:

```sql
WITH cte AS (
    SELECT 
        id,
        ARRAY<STRING>['string1', 'string2', 'string3'] AS arr
    FROM UNNEST(GENERATE_ARRAY(1, 3)) AS id

    UNION ALL

    SELECT 
        id,
        ARRAY<STRING>[] AS arr
    FROM UNNEST(GENERATE_ARRAY(1, 3)) AS id
)

SELECT * FROM cte
```

**Comment by ashish10alex** [comment]
Thanks again for reporting the issue. Please update to the latest version `v0.2.23`.
![CleanShot 2024-11-08 at 07 05 27@2x](https://github.com/user-attachments/assets/71c61581-5ff1-4ab4-adbd-f28b4508b2a0)

**Comment by HampB** [comment]
Looks good now, thanks!
