### ISSUE TITLE
feat: Improve Reauthentication Error Message

### ISSUE THREAD

**Issue by HampB** [ashish10alex/vscode-dataform-tools#53]
#### Issue
When authentication expires, users currently see the following error message:

```
{"error":"invalid_grant","error_description":"reauth related error (invalid_rapt)","error_uri":"https://support.google.com/a/answer/9368756","error_subtype":"invalid_rapt"}
```

![error message screenshot](https://github.com/user-attachments/assets/c400ac04-9f4c-4ff6-9b19-a2b13f71edc4)

This message is not very user-friendly, making it unclear how to resolve the issue. Even though most users should understand the need.

#### Suggested Improvements
- **Provide a more descriptive error message** that explains the need for reauthentication.
- **Optional: Include steps for reauthentication** or a direct link to relevant instructions.
  
A user-friendly message could look like:
> "Session expired. Please reauthenticate to continue."

This would make it easier for users to understand the issue and take corrective action without searching for additional information.

**Comment by ashish10alex** [comment]
Hi @HampB , thanks for raising the issue. Interesting, I have never seen this error before. Is there a way to reproduce this error.  Also, how do you authenticate. I use `dataform init-creds` and use the following options and have never seen this error 

![CleanShot 2024-11-14 at 12 39 39@2x](https://github.com/user-attachments/assets/41ed1575-aace-4513-9f34-783421e1d6cc)

**Comment by HampB** [comment]
Hey @ashish10alex,

For authentication, we also use `dataform init-creds` with the ADC option, which generates a `.df-credentials` file containing: `{"projectId": "value", "location": "value"}`.

However, to actually authenticate, we also need to run `gcloud auth application-default login`. This command has an expiration time of *x* hours, so after that period, the error message appears, and we need to run `gcloud auth application-default login` again.

Are we missing something here? Are you using a service account to authenticate?

**Comment by ashish10alex** [comment]
Are you using a service account to authenticate? - No, I am not. I too login with `gcloud auth application-default login` however have never seen this error. Is there some command you can run to see the number of hours left ?

**Comment by HampB** [comment]
No we do not use an service account either. Seems like the reauth policy is forced with a max of 24hr as can be seen here: https://support.google.com/a/answer/9368756

I cant seem to reproduce the error using the gcloud cli, but i'll do some more testing to try and reproduce it. (Currently the error message only shows up after leaving vscode running over 24hrs )

If nothing else i'll create PR to adress the issue and leave vscode on untill the error appears :-)

**Comment by benjaminwestern** [comment]
@HampB and @ashish10alex I experience exactly the same issue on my end, I can reproduce it by simply swapping my Google ADC to another primary email, then swapping back. As you have described @HampB, restarting the extension is the only way that I can get it to stop once occurring.

If I swap DF projects, it also persists between projects even if my credentials are working which has been validated through the extension `query` functionality and the `dataform run` operations.

**Comment by HampB** [comment]
Thanks @benjaminwestern for finding this, it will be super helpfull for testing a fix. I will try it out as soon as i get the time.

**Comment by ashish10alex** [comment]
Thanks @benjaminwestern & @HampB , I have identified at least one of the issues. 

> restarting the extension is the only way that I can get it to stop once occurring.

This is due to how dry run keeps using the BigQuery client that is generated from the first dry run invocation 
https://github.com/ashish10alex/vscode-dataform-tools/blob/7a6313402c64524f45afb6e91d3fb477cd0e9230/src/bigqueryDryRun.ts#L2

---

The easiest way to get around this is to create a new bigquery client every time you do a dry run. But I am not sue this is a good practice. Additionally this approach would have a performance penalty of ~200 to 300 ms for each invocation as it is creating the object every single time. 

---

One possible solution would be to check if there is an error followed by creating a new bigquery client object. Please feel free to suggest other ideas or send a PR.

**Comment by HampB** [comment]
Ah nice, that would explain it @ashish10alex 

Agree it's probably a bad idea to create new client each run. And since at least I would like the dry run to be as fast as possible when fixing a typo or whatever, re creating the client on all errors is probably not a good way either. (But maybe that kind of errors is handled differently already?)

Maybe could have a method to recreate the client that we can call on certain errors?

**Comment by ashish10alex** [comment]
> Maybe could have a method to recreate the client that we can call on certain errors?

This seems like a good idea for the error raised in this issue. However, I am unable to replicate the error message you reported even which constantly switching between my personal and work accounts. The only error that I get is if I change the credentials while my vscode is open. This gets fixed window is reloaded / re-open vscode. But this I assume is a rare scenario ? (maybe not ) I personally am logged in with a specific account and project that is associated with that account.

---

Please feel free to create an PR to catch the error raised in the issue. It looks like a json so should be possible to parse and filter, but would only know how robust that would be once you try it.

**Comment by benjaminwestern** [comment]
@HampB and @ashish10alex I have created a PR to resolve this and have tested it a fair bit on my side to success, basically I centralised the client creation and added a 60 minute re-check and re-create timer that is utilised for all dry run and query operations
