### ISSUE TITLE
bug: Allow previlaged users to compile queries on BigQuey tables with policy tags

### ISSUE THREAD

**Issue by icyBlue27** [ashish10alex/vscode-dataform-tools#54]
**Describe the bug**
Users which have permissions to query bigQuery tables with policy tags, get the following error when trying to run the Dataform action or compiling the query using the Dataform Tools extension
`Access Denied: Table dg-dp-dwhdata-prod:hrs_exposed.EmployeeERP: User does not have permission to query table dg-dp-dwhdata-prod:hrs_exposed.EmployeeERP, or perhaps it does not exist.`

**To Reproduce**

1. Create a BigQuery table
2. Add policy tags to some of the columns (https://cloud.google.com/bigquery/docs/column-level-security-intro)
3. Provide the user on GCP with permissions to query the columns with policy tags
4. Query the BigQuery table in a Dataform action using the extension

**Expected behavior**
Users with permissions to query the tagged columns on BigQuery should be able to query it via Dataform Tools extension

**Screenshots**
![Screenshot 2024-11-14 at 14 56 17](https://github.com/user-attachments/assets/137b70e8-74e9-4a79-82fe-84441d477c35)

**Environment:**
 - Operating system Mac and Windows (two different users)
 - Dataform cli version 3.0.0
 - Version of the extension 0.3.2

**Comment by ashish10alex** [comment]
Hi @icyBlue27 , 
thanks for raising the issue. To clarify does the issue also exists when you try to

- [ ]  dry run using dataform cli `dataform run --dry-run`
- [ ]  run dataform action using dataform cli  

or it picks up the policy tag permissions automatically ?

**Comment by icyBlue27** [comment]
Hi @ashish10alex. Thanks a lot for the quick response.
In fact, it turned out to be an issue with the configured permissions, which is currently we do not provide user credentials the permissions to set policy tags, and this Dataform action in fact has BigQuery tags for policy tags.

Sorry for the incorrect bug report. Please feel free to close this issue.
